language: java
sudo: false
install: true
addons:
  sonarqube:
    token:
      secure: SONARQUBE
    github_token:
      secure: GITHUB_TOKEN
    branches:
      - staging
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
      