dist: trusty
addons:
  sonarqube:
    token: SONAR_TOKEN
    github_token: SONAR_GITHUB_TOKEN
jdk:
  - oraclejdk8
script:
  - sonar-scanner -X
cache:
  directories:
  - "$HOME/.sonar/cache"
notifications:
  email: false
