dist: trusty
sudo: required

addons:
  sonarqube:
    token:
      secure: "na3h/3LMjI+kdbOXTZABlrhuhMXalI/TUQwKmgPX87kbc+EJePp8qNXS7S67MwXtnRyQKv7s8I8DPY/K0/R9Cjso/u1TXZvUN8IvmPw3kYfDX02+yslcFAGCBNEOSWmL1fK6MQ/jCrXDIG2i4xwS3Kuw7DFFFrYN/Ypmp5zTJxO63zwH4YHSTWpf3lJrSKjBTgrRTfBf6l9qBv6t7soPq4VH4DnDk+HWNEA92eSqa4uRYJG0kJGf+29twAWmo7oDPenwrLEvTj9asnCIdpr4kP0NfjbWQp2MspuD+rHXzwhrqixwyZ5zUv2+hmISX4rk5JuYKM51+fDIcw11gaQrJ2yE/yCe03Ll9KnB9Roy1ue/0LG2PwSa9vMNPcPptYA/EODFvs0nw5KLBZLDsh426xw6y6g1NbxExG0YPUgnzsCnJY/yyEkbgKwejTUyrqu3QsHttn1KcR0jM4Y0ih8S43RLVr7C30NpOA879ajPs3cTa24v6K7kcaRz1LhiKBnMm+X7fe+F/Pknv4gUkbt2kWKxTX4lzvDo9mfjau0Z4rmQ41OWHZWjvkEMTXtoAXRSot3lvG6fcUB7FQ9rK9fFSX9qdorFjItIOMjXg/JHdZU3qDWCE1vha/YvjCtvPFZhZakTNfI/D5Vl4zasq/gjt6GrIOV+n/m9Cxb41ryTN1o=" 
    github_token:
      secure: "r7XZ5Zmx8puRQ/cRxlQuEftbvI747kn0Sfrz0I9RpMAwT932KNVWG3/Srudi5CLB+MRw8eT2j/dD+vbUCPFkj8MydMgmDzIm/Q1pcUZjmk7jh+iFeGSFOhCc+FiinO8uKtZVhfkO0/8bYvl5SJnjZ1wo4OFDDCiv2nYUlEG9rMIdmnW9TS5WpEoebbXYQhQR9R8sIcyqGciaQ+vclz99POmA62hiEaadNLWE0ndZr9mojwz+xhRMIF0jv3ZqEOxoL+ffNIrKISGPUuDbWugTg42unEwmZmEUITIanzRomU4j6yTCtQ1rEcn0j+ESSxy+YJDFQjxZLKlMNRE+D7ybD+W2jUbAIo/vIlxi6hS6W6B7fq9SQi2mf5uDCMUh2Q12yZ8yfMzpBDEP2d3u+GiZzZKMMro4ckcAhg/iGXk8A3px03G+5g/O2CNdQffk7OycWuyjEWeLOs/q8/xvM+4cfDrZo3z2wFiX5THphxA3oFs0a8gWgHbt/e4rUzzXiLgxnugJA9vjYmZRBL41WBrzRBpPSP+T/Pmi8pGzsG3Od96XggkocepDUpyBiaEvGFnimtMEPZ6uk3yOr4p+pUoSRbuhQnLP+Ms5p4O64GX9PI1p8F8nagWcXNSwz3s7ZNcwD6vrZRo3AOSURWOGjManXokTRApYqdf7j+vURjsI3B4="

jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email: false