dist: trusty
sudo: required
addons:
  sonarqube:
    token: SONAR_TOKEN
    github_token: SONAR_GITHUB_TOKEN
jdk:
  - oraclejdk8
script:
  - sonar-scanner -Dsonar.analysis.mode=preview \
              -Dsonar.github.repository=MediaMath/t1-java \
              -Dsonar.github.oauth=SONAR_GITHUB_TOKEN \
              -Dsonar.host.url=https://sonarqube.com \
              -Dsonar.login=SONAR_TOKEN \
              -Dsonar.projectKey=mediamath:t1-java \
              -Dsonar.sources=.
cache:
  directories:
  - "$HOME/.sonar/cache"
notifications:
  email: false
